### ISSUE TITLE
convert QGIS data to EPANET reading format (INP)

### ISSUE THREAD

**Issue by Inno100sami** [JinIgarashi/postgis2epanet#3]
postgis2epanet is very useful tool. Model building take long time, but by using this tool, the work is being easy. It requires only EPANET model calibration. but the installation guide of this tool is needed to be quite clear.
Another encountered problem is that auto length is not working because the used shapefiles are in decimals projection (EPSG 4326). 
I wish you change projection from decimals to UTM so that we may add new pipes and auto length works successfully.
![image](https://user-images.githubusercontent.com/71173062/93771100-58114780-fc1d-11ea-97c8-e0734e2a63fa.png)
But using UTM projection, Auto length works as shown in this picture:
![image](https://user-images.githubusercontent.com/71173062/93771771-3c5a7100-fc1e-11ea-840a-ba279b0f1ef2.png)

Thank you Jin!

**Comment by JinIgarashi** [comment]
@mirankunda I fixed this issue. Could you update source code and regenerate INP files?
```
cd postgis2epanet
docker pull wasac/postgis2epanet:v2.0.1
docker-compose up
```

@Inno100sami Please check new INP files after Moise share with you.
